#配置Postgres
#层1：版本
version: '3.9'
#层2：服务
services:
  db:
    #配置postgres镜像并指定15-alpine版本
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    #配置环境变量,创建用户postgres，密码postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # 👇 核心魔法在这里：由 Docker Compose 负责拼接，然后注入到容器环境变量中
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    #挂载数据卷，挂载到宿主机的/data/db_data目录下，防止数据丢失
    #创建数据卷，数据卷名称为db_data
    #./healthchecks:/healthchecks是健康检查脚本，从本地目录healthchecks复制到容器的/healthchecks目录下
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    #配置网络,创建网络名称为back-tier，意思是将db服务加入到back-tier网络中，即
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh /healthchecks/postgres.sh"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s

  #配置ChromaDB
  chroma:
    image:  chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - "chroma_data:/chroma"
    networks:
      - backend
    environment:
      - IS_PERSISTENT=TRUE
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v2/heartbeat')"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s

#层3：环境变量
volumes:
  db_data:
  chroma_data:

networks:
  backend:




